#! /bin/sh

# set wallpaper
feh --bg-scale ~/dotfiles/wallpapers/blueorange.png

# Polybar
sh ~/.config/polybar/launch.sh &

# compositor
compton &

# automatic usb mounter
udiskie &

# autostart programs
kitty &
redshift &
