#! /bin/sh

# Polybar
sh ~/.config/polybar/launch.sh &

kitty &
keeweb &

# focus on desktop 1
bspc desktop -f ^1 &

# set wallpaper
feh --bg-scale /usr/share/backgrounds/gnome/adwaita-night.jpg &

# start compositor
compton &

